version: "v2.23.0-desktop.1"
services:
  frontend:
    build: ./containerization-front-end
    container_name: frontend-container
    ports:
      - "3750:3750"
  backend:
    build: ./containerization-back-end
    container_name: backend-container
    ports:
      - "3751:3751"
    environment:
      DATABASE_URL: mongodb://mongo-db/messages
  mongo-db:
    image: mongo:4.0-xenial
    container_name: mongo-db-container
    ports:
      - "27017:27017"
    volumes:
      - containerization-example-mongo-data:/data/db
volumes:
  containerization-example-mongo-data: