version: "3.8"
services:
  frontend:
    build: ./containerization-front-end
    container_name: frontend-container
    ports:
      - "3750:3750"
  backend:
    build: ./containerization-back-end
    container_name: backend-container
    ports:
      - "3751:3751"
    environment:
      DATABASE_URL: mongodb://admin:admin@mongodb
  mongodb:
    build:
        context: .
        dockerfile: Dockerfile-mongo
    volumes:
      - mongodata:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: messages
volumes:
  mongodata: